name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  manubot:
    name: Manubot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Build Manuscript
        env:
          GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
        shell: bash --login {0}
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
      - name: Deploy Manuscript
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
          BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
        shell: bash --login {0}        
        run: |
          if [ "$MANUBOT_SSH_PRIVATE_KEY" != "" ]; then
            bash ci/deploy.sh
          else
            echo >&2 "Skipping deployment because the MANUBOT_SSH_PRIVATE_KEY secret is not set.
            Instructions at https://github.com/manubot/rootstock/blob/master/SETUP.md#deploy-key"
          fi
